### PR TITLE
Fixed documentation compliance

### LINKED ISSUE #488: Fix documentation compliance
Per https://github.com/BHoM/BHoM_UI/pull/487/checks?check_run_id=22829623272

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #488 

Fixed documentation compliance, and some fixes to code compliance (namely extension method fixes, though ignoring input/output accessor fails).

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
All looks good, thanks @Tom-Kingstone - approving on code review

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
