### PR TITLE
Trigger for UI Loading events during analytics logging

### LINKED ISSUE #437: Race Condition in loading scripts
#### Description:

In Grasshopper, since the projectId is set by canvas node/compute method, it is possible that other canvas nodes/methods would compute before the projectID method creates the projectIDEvent. Users are reporting that they still get the popup even though the setprojectID canvas node/method was set in previous sessions. 

Revit/Excel retrieve the projectId value from queryable internal data fields and do not require a compute of a projectIDEvent to set the projectId, so I do not expect this to be an issue in these toolkits. 

We've not yet set up any method of pre-setting the projectId in Dynamo, but were we to do so, I would expect this to occur in Dynamo as well. 

#### Steps to reproduce:

open GH file that has multiple compute methods on the canvas 

#### Expected behaviour:

I would expect that the projectID could be set/compute before all others, however we did not program this to act in this way.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #437

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Review by jamesramsden-bh — APPROVED** [review]
Tested locally, reopening a previously assigned script now no longer triggers the analytics popup. Changing the project number, saving, and reopening the script triggers the popup again on GH recalculation.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, project-compliance, ready-to-merge, versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by CKBoulter — APPROVED** [review]
Approving following copyright updates based on functionality review previously provided.

**Pull request merged**
