### PR TITLE
Enum.GetNames replaced with IToText on enum label generation to leverage DisplayText attribute

### LINKED ISSUE #447: Pick DisplayText attribute of enums while generating their labels
#### Description:

As in the title: currently the labels of enums are generated using `Enum.GetNames()`, which means that `DisplayTextAttribute` is not leveraged at all by the UI.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #447

### Test files

Create `DensityExtractionType` enum in Grasshopper and see if the first option shows as `AllMatching` (current) or `All matching.` (desired).

### CODE REVIEW

**Review by adecler — APPROVED** [review]
Thanks @pawelbaran ,

The code change makes sense and we now have the expected behaviour in the UI:
image

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
