### PR TITLE
BHoM_UI: Added outputs and changed adapter descriptions to match. #107

### LINKED ISSUE #107: BHoM_UI: Align output names and descriptions
Add output names where missing (Move, Execute, Pull) and align the descriptions for different components (for example, success for Move and Push are described differently).

image

### PR DESCRIPTION
**Pull request by LivAndersson**
### Issues addressed by this PR

Closes #107 
Output names added and descriptions aligned
image

### Additional comments
N/A

### CODE REVIEW

**Comment by LivAndersson** [comment]
Thanks for the feedback! Will keep in mind for the future.

And NO, that is not intended! I have tried to change it but have clearly not succeeded. If you know how to fix it, please give me a shout!

**Comment by al-fisher** [comment]
> committing with credentials that are different 

@LivAndersson - are you using GitHub Desktop? The username/email address in the GitHub desktop can get out of sync. Worth having a look to see if that is the email you expect

**Comment by LivAndersson** [comment]
@al-fisher Nope, I'm on GitBash.. have changed credentials in my credential manager but it doesn't seem to come through

**Comment by epignatelli** [comment]
Even using the `--global` flag? https://help.github.com/en/articles/setting-your-commit-email-address-in-git

**Comment by LivAndersson** [comment]
@epignatelli That I had not. Thanks! Will try.

**Comment by epignatelli** [comment]
hey @LivAndersson, the BHoM_UI is now unlocked, since the existing pr has been merged.
The right way to merge this one, would be to close this, create a clean branch from the current master HEAD and pr.

Although, I don't think there should be conflicts - I'll try to skip the above and merge straight away.

In the details of the code, what I see is different from the picture you posted,
Is it intentional, or is there any code left behind?
image

**Comment by LivAndersson** [comment]
It's intentional - I updated it as I realised it didn't follow the conventions of other components. 
Have a good day!

image

**Comment by epignatelli** [comment]
Thanks @LivAndersson !

**Pull request merged**
