### PR TITLE
Add event to be triggered when the UI is closing

### LINKED ISSUE #434: Add an event to be triggered when the UI is closed
As title, allow other toolkits to know when the BHoM UI is closing.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #434

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check versioning

**Review by kprusicka — APPROVED** [review]
Looks incredible to me

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by travispotterBH — APPROVED** [review]
Log is amended at closing for Excel document: 
image

**Pull request merged**
