### PR TITLE
Fix target framework in the nuspec file

### LINKED ISSUE #493: Fix the nuspec template file to reference the correct framework
#### Description:
See code here where the framework is set to `netstandard2.0.0` instead of `netstandard2.0`:
https://github.com/BHoM/BHoM_UI/blob/9e02387d51cabc044d9e571f759cb1c4f0097b0f/.ci/BHoMBot/Nuget/BHoM.UI.nuspec#L18

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #493 

Fairly straightforward. I simply removed the extra `.0` in the target framework. So this should be pretty quick and easy to review.

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Review by IsakNaslundBh — APPROVED** [review]
Approved by code inspection and happy with the change.

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
