### PR TITLE
Update Reflection -> Base on CI verification code

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Updates usings in the CI verification code following the Reflection changes.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, versioning

**Comment by FraserGreenroyd** [comment]
I have neutralised the heavy checks owing to the changes being solely limited in scope to CI verification code, and not code which will impact the primary UI functionality.

**Review by IsakNaslundBh — APPROVED** [review]
Builds fine on my machine. 

Code review shows that the only changes made are alignments from previous refactor of oM and Engine. Approved

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6936663584

**Pull request merged**
