### PR TITLE
Update CI files

### LINKED ISSUE #194: Update compliance test file and turn on compliance checking option
Update `.ci/run-compliance-tests.yml` to reflect the DLL name change in Test_Toolkit and then turn on compliance checking for this repository.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #194 

### Additional comments
If the ticks are green it's good to go

### CODE REVIEW

**Comment by epignatelli** [comment]
Is this still wip?

**Comment by FraserGreenroyd** [comment]
No @epignatelli it's good to merge whenever, sorry, forgot to remove label!

**Pull request merged**
