### PR TITLE
Load settings on loading of UI

### LINKED ISSUE #467: Load settings from Settings Engine on load of a UI.
Settings_Engine in the UI allows for loading settings - should be called on UI load to ensure settings are booted into memory ready for use.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #467

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by Tom-Kingstone — APPROVED** [review]
Loading UI now loads settings and works with no errors.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer, ready-to-merge

**Pull request merged**
