### PR TITLE
Add file ID to trigger of usage args

### LINKED ISSUE #426: Stop using ProjectIDEvent to pass the project ID to analytics - add one more LogUsage method parameter instead
#### Description:

As in the title, currently to log the project ID in analytics, one needs to raise `ProjectIDEvent`, which is then magically passed to the usage logs. Besides this being overly complicated, it makes no sense for practical reasons: project ID can be set only once per session, but what if I work on two projects in parallel?

Instead, we could simply add one more parameter to the `LogUsage` method, where the project ID would be set. Besides simplicity and elegance, this would also bring more flexibility, letting each of the UIs control the source and value of the ID parameter.

### LINKED ISSUE #428: Ability to track usage per file in addition to per session
Per title, allow the ability to track BHoM usage per file that it is used for project IDs in addition to the usage per session.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #428 - don't read the issue thread though 🤕 
Fixes #426 - not in the way the issue describes but in a suitable way for the desires of the workflows

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting a force check on: installer

**Review by travispotterBH — APPROVED** [review]
Works for multi document/file analytics. Issue with setting project Id on documents to avoid popup to be resolved in another PR. Approved.

**Review by EKAdebo — APPROVED** [review]
Analytics pop up appears when you change to BHoM scripts in Grasshopper or Excel workbooks.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
