### PR TITLE
Add Information component for UI elements and update GetInfo to include full install version information

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes https://github.com/BHoM/BHoM_Engine/issues/2971

### Additional comments
Also adds the install date to `GetInfo`

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance
@BHoMBot check core
@BHoMBot check installer

**Comment by travispotterBH** [comment]
Tested in Grasshopper: 
image


Tested in Excel:
2023-01-24 14_31_14-Window

**Review by travispotterBH — APPROVED** [review]
Looks good. Next steps is for each toolkit UI to decide how to implement.

**Comment by travispotterBH** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge

**Pull request merged**
