### PR TITLE
Add test scripts for core UI

### LINKED ISSUE #347: CI: Add test script for versioning toolkit
#### Definition of the test :
This test should run a serialisation cycle on all types available on the BHoM. 
This should be written in C# in the `.ci\code` folder.

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/2251
https://github.com/BHoM/Test_Toolkit/pull/311
   
### Issues addressed by this PR

Closes #347 

This provides 3 series of tests:
- Make sure that all items available from the components' menu can be used to generate a valid component
- Test if all the possible components in the BHoM can be copied/saved without error
- Check that all parameters (input/output) are handled correctly without error. This uses a dummy component that behaves exactly like the other to the difference that it doesn't run the selected item and generates dummy outputs of the expected types instead. 

### Test files
Use the `TestRunner` with the `UI` argument

### CODE REVIEW

**Comment by adecler** [comment]
FYI, I have now rebased this branch to make sure it merges nicely with the master

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by FraserGreenroyd — APPROVED** [review]
An issue with the copyright where BHoMBot doesn't seem to want to check the CI files but I'll handle that one later and do a new PR resolving that because I'm happy with the overall content on this PR and how this is working with the TestRunner.

I ended up with failures when I ran it but that will no doubt now be the basis for fixes down the line as I presume we knew we wouldn't have 100% success on the first runs.

So happy with this PR and the others, merging and looking forward to the next phases :smile:

**Pull request merged**
