### PR TITLE
Add nuspec template file

### LINKED ISSUE #464: Add nuspec file
To the folder `.ci/BHoMBot/Nuget` - in the form of `{repository_name}.nuspec` to help the bot automatically produce nugets of this repository.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #464

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: code-compliance, copyright-compliance, core, documentation-compliance, installer, project-compliance, ready-to-merge, serialisation, versioning, dataset-compliance, unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: null-handling

**Review by peterjamesnugent — APPROVED** [review]
Reviewed by inspection.

**Review by Dhorix — APPROVED** [review]
Great, looks okay

**Pull request merged**
