### PR TITLE
Make sure that IEnumerable of generics are handled properly

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/2367

   
### Issues addressed by this PR
See https://github.com/BHoM/BHoM_Engine/pull/2367

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@IsakLarbornBH , you already reviewed and approved https://github.com/BHoM/BHoM_Engine/pull/2367. Can you also approve this one, please ?

**Review by IsakLarbornBH — APPROVED** [review]
Approved through my testing done for BHoM/BHoM_Engine#2367.

**Pull request merged**
