### PR TITLE
Improve support to generic types

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/1565

 
### Issues addressed by this PR
Closes https://github.com/BHoM/BHoM_UI/issues/45

This improves significantly support for generic meethods in the UI. See test file for what I have covered. Feel free to list everything that is not yet supported even with this.

This PR doesn't aim at solving all existing problems with generics but to provide a step in the right direction. I have also taken as much precaution as possible to isolate teh code for cases where problems occur with generics. So HOPEFULLY it should brake anything that was previously working. In doubt I would rather merge next quarter.

This takes care of :
- recomputing dynamically input getter when generic input type is not matching
- recomputing dynamically compiled method when generic input types are not matching
- recomputing dynamically input setter when generic output type is not matching

### Test files
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_UI/BHoM_UI-%2345-GenericTypes.gh?csf=1&e=KdeXau

### CODE REVIEW

**Comment by adecler** [comment]
Thanks @IsakNaslundBh . Both really good catch. 
Should now be fixed with the last two commits.

**Comment by adecler** [comment]
@IsakNaslundBh , Can you do a second pass on your review ? I don't want to dismiss your request for change as it is a PR that I don't want to merge lightly.

**Comment by IsakNaslundBh** [comment]
Yes, sorry, will have another pass thorugh

**Comment by adecler** [comment]
@IsakNaslundBh , well technically the feature was implemented in this PR and was working for most cases. I just forgot that a structural panel is not a generic type (only IPanel is). So the code supposed to handle the update was not triggered 😋 .
Now fixed with the latest commit.

**Comment by IsakNaslundBh** [comment]
@al-fisher @FraserGreenroyd is there any fix the failing appveyor CI?

**Comment by FraserGreenroyd** [comment]
> @al-fisher @FraserGreenroyd is there any fix the failing appveyor CI?

I've triggered it to re-run as it looked like it had a problem which may have since been resolved. Hopefully it'll come back green in a few minutes for you @IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
@FraserGreenroyd still no luck. Seems like the CI has not properly managed to merge the engine branch to master when comparing (UI master is complaining about a missing Engine method that do exist on mater)

**Comment by al-fisher** [comment]
@FraserGreenroyd CI was solved by merging the Engine to ensure it was being picked up correctly. I could not get to the bottom of why AppVeyor was behaving strangely for this PR I am afraid. Added a ref to this PR on [issue here](https://github.com/BHoM/Test_Toolkit/issues/188)

**Pull request merged**
