### PR TITLE
Isolate the CodeEditor in a separate dll for optional loading

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
Used by https://github.com/BHoM/Grasshopper_Toolkit/pull/591

   
### Issues addressed by this PR

Closes https://github.com/BHoM/Dynamo_Toolkit/issues/289

See issue. To solve the problem, I have isolated the code that uses AvalonEdit into a separate dll so each UI can chose whether or not it loads it. 

### Test files
Just make sure that the CodeBlock in Dynamo is working again while the RunCode component in Grasshopper is still working

### CODE REVIEW

**Review by pawelbaran — DISMISSED** [review]
Looks like it solves the problem. LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Can the DLLs highlighted be set to copy local false? Could try BHoMBot fix if you want :smile:

The one on Versioning_Engine can be ignored, looks like it's a bit eager about the word `Version` 🙄

**Comment by adecler** [comment]
@BHoMBot check project compliance

**Comment by adecler** [comment]
@FraserGreenroyd , done.
I wonder if it is still necessary to have a compliance rule about copy local since we have to explicitly copy to ProgramData in post build. So we don't have the same issue of duplicated dll as before.

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Review by pawelbaran — APPROVED** [review]
Still LGTM 👍

**Comment by FraserGreenroyd** [comment]
@BHomBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1768304164

**Review by FraserGreenroyd — APPROVED** [review]
LGTM :smile:

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd , done.
> I wonder if it is still necessary to have a compliance rule about copy local since we have to explicitly copy to ProgramData in post build. So we don't have the same issue of duplicated dll as before.

Just confirming discussion in stand up but for others too, copy local will cause problems with Nuget scraping when we get to that, so keeping this check for now :smile:

**Pull request merged**
