### PR TITLE
Align with changes in oM and Engine on Reflection -> Base

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1339
https://github.com/BHoM/BHoM_Engine/pull/2729

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 4788179936

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Review by adecler — APPROVED** [review]
I did a minor correction on a duplicate `using` but otherwise looks good. 
The BHoM_UI is heavily using reflection (e.g. for the attribute methods) so not critical to trim the `using` references to the reflection engine.

**Comment by adecler** [comment]
As per [comment in the Excel_Toolkit PR](https://github.com/BHoM/Excel_Toolkit/pull/327#issuecomment-1011843086), I fixed the broken `SetProperty` component.

**Review by adecler — APPROVED** [review]
Now all seems to be good

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, code-compliance, copyright-compliance, dataset-compliance, documentation-compliance, null-handling, project-compliance, ready-to-merge, serialisation

**Pull request merged**
