### PR TITLE
Add event for when the UI is finished opening

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Allows events to hook onto when the UI has finished opening.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by jamesramsden-bh — APPROVED** [review]
Tested against test procedure for analytics, all fine.

**Pull request merged**
