### PR TITLE
Fix explode of Custom Object with a nested list property

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes https://github.com/BHoM/BHoM_Engine/issues/2674

### Test Files

[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FUI%2F%23469%2DExplodeCustomObject&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b). The JSON used has come from @tg359 on the linked issue which this PR aims to resolve.

On alpha:

image

On this PR:

image

If testing using the provided test script **please make sure** you redrag the output of `FromJson` into the `Explode` component to get it to update. Alternatively, drop a new `Explode` component on the canvas and compare the cached one with the one from this PR.

E.G:

image

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 16280314097

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 16281528423

**Comment by adecler** [comment]
To summarise the discussion I just had with @FraserGreenroyd , I feel that this PR doesn't address the underlying problem of the deserialisation of lists of lists that comes from an external serialisation source. So this PR runs the risk of masking the problem instead of fixing it. 

See below the resulting serialisation of a List of lists fully created within the BHoM vs the one coming coming from a deserialisation of external json:

image

As you can see, the later generates 'messier' json independently of the Explode issue addressed here. If that deserialisation is resolved, the Explode issue should go away.

We might still need to improve the Explode component if we find other cases of `List<T>` represented as `List<object>` or even lists of objects that contain multiple types (including `List<T>`) but then the PR should be done addressing the problem in its larger context, not just this one caused by serialisation.

**Comment by FraserGreenroyd** [comment]
Closing this in favour of [this PR](https://github.com/BHoM/BHoM_Engine/pull/3160) - we can reopen this if needed

**Pull request closed without merging**
