### PR TITLE
Add ability to create a DateTime type from the CreateType component

### LINKED ISSUE #391: Add ability to create a DateTime type from the CreateType component
The CreateType component can create a series of System types but not the `System.DateTime` type.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #391 

See issue

### Test files
Just try to create a `DateTime` type from the `CreateType` component and make sure that it works

### CODE REVIEW

**Review by BingWangUS — APPROVED** [review]
Tested and works well. Resolve the custom object type in excel as well.

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check versioning

**Comment by adecler** [comment]
@BHoMBot check core

**Pull request merged**
