### PR TITLE
Remove the ability to create typed objects from the CreateCustom component

### LINKED ISSUE #159: Remove the ability to create typed objects from the CreateCustom component
#### Broken rules:
This feature is now supported directly by `CreateObject` so no need for duplicates

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #159

### Test files
Just make sure that the CreateCustom component is not allowing you to select a type from its menu and that it is still working for creating custom objects

### Additional comments
Make sure to also check [the PR in Excel_Toolkit](https://github.com/BHoM/Excel_Toolkit/pull/170) as some changes were needed there to keep it compiling

### CODE REVIEW

**Comment by adecler** [comment]
@epignatelli , weird, it works perfectly fine for me:

image

Which makes sense because nothing in the code I have changed on this PR could trigger that effect. Are you sure you are on the correct version for all repos?

**Comment by epignatelli** [comment]
Yeah, that's very weird, but I agree with you, I was surprised in the first place.

What I don't actually understand is how it can be working now, without that check.
I'll re-check and make sure the branch set is correct!

**Comment by epignatelli** [comment]
@adecler is there anything that prevents us from merging this?

**Comment by adecler** [comment]
@epignatelli , yes, Excel_Toolkit needs to be updated first as this PR was preventing it from compiling. 

I did a quick attempt to fix it in https://github.com/BHoM/Excel_Toolkit/pull/170 but it was apparently a bit too quick 😋 . @awakeman is now on it to do that properly.

**Comment by epignatelli** [comment]
Ah, right, ok! I'll add a do-not-merge then, waiting for BHoM/Excel_Toolkit#170 to be closed.

**Pull request merged**
