### PR TITLE
Search in dropdowns unlocked

### LINKED ISSUE #449: Add search in dropdowns
#### Description:

As in the title, it has been requested on a few different occasions. Sometimes the dropdowns become very long (e.g. RHS steel sections), which makes them hard to navigate and pretty sluggish (Grasshopper). A search similar to what we have when selecting type etc. would be massively helpful.

image

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #449

### Test files

Try creating and navigating dropdowns (enums, datasets) - search bar should be available under right click now.

### CODE REVIEW

**Review by adecler — APPROVED** [review]
Works very well. Love that it applies to both the enum and database dropdowns.

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
