### PR TITLE
Add ability to query the usage log file name for external toolkits to the UI

### LINKED ISSUE #431: Extend deprecation period for usage logs
As title, extend to 28 days (1 month).

### LINKED ISSUE #432: Query to get the current usage log file
Externally to the UI - ability to get the current usage log file name.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #432 
Fixes #431

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by kprusicka — COMMENTED** [review]
Looks good to me

**Review by kprusicka — APPROVED** [review]
I've never seen anything more perfect.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
